<h1>NumPy Basics<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#NumPy-array----ndarray" data-toc-modified-id="NumPy-array----ndarray-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>NumPy array -- ndarray</a></span><ul class="toc-item"><li><span><a href="#creating-arrays" data-toc-modified-id="creating-arrays-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>creating arrays</a></span></li><li><span><a href="#NumPy-data-types" data-toc-modified-id="NumPy-data-types-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>NumPy data types</a></span></li><li><span><a href="#type-casting" data-toc-modified-id="type-casting-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>type-casting</a></span></li></ul></li><li><span><a href="#Indexing-&amp;-Slicing" data-toc-modified-id="Indexing-&amp;-Slicing-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Indexing &amp; Slicing</a></span><ul class="toc-item"><li><span><a href="#basic-indexing-&amp;-slicing" data-toc-modified-id="basic-indexing-&amp;-slicing-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>basic indexing &amp; slicing</a></span></li><li><span><a href="#boolean-indexing" data-toc-modified-id="boolean-indexing-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>boolean indexing</a></span></li><li><span><a href="#fancy-indexing" data-toc-modified-id="fancy-indexing-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>fancy indexing</a></span></li><li><span><a href="#transpose-and-axes-permutation" data-toc-modified-id="transpose-and-axes-permutation-2.4"><span class="toc-item-num">2.4&nbsp;&nbsp;</span>transpose and axes permutation</a></span><ul class="toc-item"><li><span><a href="#matrix-transpose" data-toc-modified-id="matrix-transpose-2.4.1"><span class="toc-item-num">2.4.1&nbsp;&nbsp;</span>matrix transpose</a></span></li><li><span><a href="#axes-permutation" data-toc-modified-id="axes-permutation-2.4.2"><span class="toc-item-num">2.4.2&nbsp;&nbsp;</span>axes permutation</a></span></li></ul></li></ul></li><li><span><a href="#Arithmetics-&amp;-Element-Wise-Functions-(Universal-Functions)" data-toc-modified-id="Arithmetics-&amp;-Element-Wise-Functions-(Universal-Functions)-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Arithmetics &amp; Element-Wise Functions (Universal Functions)</a></span><ul class="toc-item"><li><span><a href="#list-of-ufuncs" data-toc-modified-id="list-of-ufuncs-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>list of ufuncs</a></span></li></ul></li><li><span><a href="#Array-Oriented-Programming" data-toc-modified-id="Array-Oriented-Programming-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Array-Oriented Programming</a></span><ul class="toc-item"><li><span><a href="#where()" data-toc-modified-id="where()-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>where()</a></span></li><li><span><a href="#statistical-methods" data-toc-modified-id="statistical-methods-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>statistical methods</a></span></li><li><span><a href="#sorting" data-toc-modified-id="sorting-4.3"><span class="toc-item-num">4.3&nbsp;&nbsp;</span>sorting</a></span></li><li><span><a href="#set-operations-on-1-dim.-arrays" data-toc-modified-id="set-operations-on-1-dim.-arrays-4.4"><span class="toc-item-num">4.4&nbsp;&nbsp;</span>set operations on 1-dim. arrays</a></span></li></ul></li><li><span><a href="#Linear-Algebra" data-toc-modified-id="Linear-Algebra-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Linear Algebra</a></span></li><li><span><a href="#Pseudorandom-Number-Generation" data-toc-modified-id="Pseudorandom-Number-Generation-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Pseudorandom Number Generation</a></span></li><li><span><a href="#Broadcasting" data-toc-modified-id="Broadcasting-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Broadcasting</a></span></li></ul></div>

last update: 2018/06/15

In [4]:
import numpy as np

# NumPy array -- ndarray
An `ndarray` is a **multidimensional** container for **homogeneous** (i.e., of the same type) data.

In [12]:
a = np.array([[0,1,2], [3,4,5]])
type(a)

numpy.ndarray

In [47]:
print('dtype:', a.dtype)  # element data-type
print('itemsize:', a.itemsize)  # bytes per element

dtype: int64
itemsize: 8


In [46]:
print('ndim:', a.ndim)   # number of dimensions
print('shape:', a.shape)  # sizes of the dimensions
print('size:', a.size)   # total number of elements

ndim: 2
shape: (2, 3)
size: 6


## creating arrays

In [ ]:
# from seqeunce-like object
arr = np.array([[0,1,2], [3,4,5]], dtype=np.float64)
arr = np.array(((0,1),(2,3),(4,5)))

# zeros, ones, empty, full
np.zeros((2, 3))  # a 2x3 array, all elements initialized to 0
np.ones((2, 3))   # a 2x3 array, all elements initialized to 1
np.empty((2, 3))  # a 2x3 array, elements not initialized
np.full((2,3), np.pi)

arr = np.array((0,1,2))
np.zeros_like(arr) # returned array will be of the same *shape* and *dtype* as `arr`
np.ones_like(arr) 
np.empty_like(arr)
np.full_like(arr, np.pi)  # [3,3,3]

# arange
np.arange(4)  # [0,1,2,3]
np.arange(0, 10, 2)  # start, stop (exclusive), step
                     # [0, 2, 4, 6, 8]

np.arange(0.0, 0.4, 0.1)  # float arguments: use with care
                          # [0.0, 0.1, 0.2, 0.3, 0.4]
np.arange(0.0, 0.3001, 0.1)  # [0.0, 0.1, 0.2, 0.3]

# identity matrix
np.identity(3)
np.eye(3)

## NumPy data types
* `int8, int16, int32, int64`
* `uint8, ..., uint64`
* `float16, ..., float128`
* `complex64, ..., complex256`
* `bool`, `object`
* `string_` (fixed-length ASCII string)
* `unicode_` (fixed-length Unicode string)

## type-casting

In [ ]:
# using `astype()`
# `astype()` always creates a new array.

a = np.array([0,1,2,3])
a2 = a.astype(np.float64)  # [0., 1., 2., 3.]

a = np.array([0.5, 1.5, 2.5, 3.5])
a2 = a.astype(np.int32)  # [0, 1, 2, 3]

a = np.array([0.5, 1.5, 2.5])
arr_string = a.astype(np.string_)  # [b'0.5', b'1.5', b'2.5']
arr_string.astype(np.float64)  # [0.5, 1.5, 2.5]

# Indexing & Slicing
## basic indexing & slicing

In [20]:
a = np.array([1,2,3,4])

# create a slice, which is a view, of `a`
b = a[0:2]
b[0] = 100  # now `a` becomes [100,2,3,4]

a[0:2] = 9  # now `a` becomes [9,9,3,4]
b[:] = 9  # same effect

# beware of the type of the array
a[0] = 10.23  # a[0] will be 10, as the array is of int type

* *Note.* Array slices are **views**, unlike the slices of a Python list.

In [ ]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])

a[0,2]  # 3, same as a[(0,2)], a[0][2]
b = a[0]  # [1,2,3], a view

a[:2]  # [[1, 2, 3], [4, 5, 6]]
a[:2, 1:]  # [[2, 3], [5, 6]]

a[:2, 1]  # [2,5]
a[:2, 1:2]  # [[2],[5]]

## boolean indexing

In [ ]:
a = np.array([0,1,2,3])
b = np.array(['A','B','C','D'], dtype=np.string_)

a[[True,False,False,True]]  # [0,3], a shallow copy (not a view)
b[a==2]  # [b'C'], a shallow copy (not a view)
b[a==2] = 'Z'  # now `b` becomes [b'A', b'B', b'Z', b'D']

(a==2) | (a==3)  # [False, False, True, True]
#(a==2) or (a==3)  # won't work

In [ ]:
a = np.array([[0,1,2],[3,4,5],[6,7,8]])

a[np.array([False,True,False])]  # [[3, 4, 5]]
a[np.array([False,True,True]), 1:]  # [[4, 5], [7, 8]]

a[a%2==0]  # [0,2,4,6,8]  (a 1D array)

## fancy indexing

In [ ]:
a = np.array([0,10,20,30,40])
a[[1,0,-1]]  # [10,0,40], a shallow copy (not a view)

In [ ]:
a = np.array([[0,1,2],[3,4,5],[6,7,8]])
a[[0,2]]  # [[0, 1, 2], [6, 7, 8]]
a[1, [0,2]]  # [3, 5]
a[1:2, [0,2]]  # [[3, 5]], a shallow copy

If all dimensions of an array are indexed using fancy indexing, the result is always 1-dimensional:
\begin{equation}
  A[\,[i_1,i_2,\ldots,i_n], [j_1,j_2,\ldots,j_n], [k_1,k_2,\ldots,k_n]\,]
  = [ A_{i_1 j_1 k_1}, A_{i_2 j_2 k_2}, \ldots, A_{i_n j_n k_n} ]
\end{equation}
where $A$ is assumed 3-dimensional.

In [ ]:
a = np.array([[0,1,2],[3,4,5],[6,7,8]])
a[[0,2], [1,1]]  # [1, 7] (which is [a01, a21])

## transpose and axes permutation
### matrix transpose

In [9]:
a = np.array([[0,1,2],[10,11,12]])

a.transpose()  # returns transposed matrix, which is a view of the original matrix
a.T  # same

array([[ 0, 10],
       [ 1, 11],
       [ 2, 12]])

### axes permutation
Dimension permutation of $M$-dimensional array:

If `B = A.transpose((`$p_0,p_1,\ldots,p_{M-1}$ `)),` where $(p_0,p_1,\ldots,p_{M-1})$ must be a permutation of $(0,1,\ldots,M-1)$,
then
\begin{equation}
  B[i_{p_0}, i_{p_1}, \ldots, i_{p_{M-1}}] = A[i_0, i_1, \ldots, i_{M-1}] .
\end{equation}

In [23]:
list1 = ['{:03d}'.format(i*100+j*10+k)  for i in range(3)  for j in range(2)  for k in range(3)]
a = np.array(list1).reshape(3,2,3)
print(a)

[[['000' '001' '002']
  ['010' '011' '012']]

 [['100' '101' '102']
  ['110' '111' '112']]

 [['200' '201' '202']
  ['210' '211' '212']]]


In [28]:
b = a.transpose((1,2,0))  # b_jki = a_ijk   # returned is a view
print(b)

[[['000' '100' '200']
  ['001' '101' '201']
  ['002' '102' '202']]

 [['010' '110' '210']
  ['011' '111' '211']
  ['012' '112' '212']]]


In [ ]:
# swapaxes() takes 2 parameters:
c = a.swapaxes(0,1)  # c_ijk = a_jik   # returned is a view

# Arithmetics & Element-Wise Functions (Universal Functions)

In [ ]:
# element-wise operations
a1 = np.array([[ 1, 2], [ 3, 4]])
a2 = np.array([[10,20], [30,40]])

a1 + a2
a1 * 2
a2 ** 0.5

a1 > 2   # a boolean array
(a2-a1)%2 == 0  # a boolean array

In [ ]:
# unary ufuncs
a = np.arange(8)
np.sqrt(a)
np.exp(a)

# binary ufuncs
x = np.random.rand(8)
y = np.random.rand(8)
np.maximum(x,y)

In [ ]:
a = np.random.rand(5) * 30
print(a)

frac, integral = np.modf(a)  # returns 2 arrays (fractional parts, integral parts)
print(frac)
print(integral)

In [5]:
# in-place operation
arr = np.arange(0.0, 8.01)
np.sqrt(arr, out=arr)
arr

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712])

## list of ufuncs
* unary
  * `abs, fabs`
  * `sqrt, square, exp`
  * `log, log10, glo2, log1p` (computes $\log(1+x)$)
  * `sign, ceil, floor,` `rint` (round, rounding half to even)
  * `modf` (get fractional and integral parts)
  * `isnan, isfinite, isinf`
  * `cos, cosh, sin, sinh, tan, tanh`
  * `arccos, arccosh,` etc.
  * `logical_not`
* binary
  * `add, subtract, multiply, divide, floor_divide, power`
  * `maximum, minimum, fmax, fmin` (fmax, fmin ignores NaN)
  * `mod`
  * `copysign` (copy sign of 2nd arg. to 1st arg.)
  * `greater, greater_equal, less, less_equal, equal, not_equal`
  * `logical_and, logical_or. logical_xor`

# Array-Oriented Programming

In [53]:
# example -- compute z = (x^2 + y^2)^0.5 at mesh points
pnts = np.arange(-5, 5.0001, 0.1)  # 101 equally spaced points
(xs, ys) = np.meshgrid(pnts, pnts)  # create a mesh grid

zs = np.sqrt(xs**2 + ys**2)

## where()
`where(<condition>, x, y)` is the vectorized version of the ternary expression `x if <condition> else y`

In [ ]:
xarr = np.array([ 1,  2,  3,  4])
yarr = np.array([11, 12, 13, 14])
cond = np.array([True, False, False, True])

a = np.where(cond, xarr, yarr)  # [ 1, 12, 13,  4]

In [ ]:
# example
a = (np.random.rand(25) * 20).reshape(5,5)

b = np.where(a>10, 10.0, a)  # `b` will be `a` limited to <= 10

## statistical methods
* aggregation
    * `sum, mean, std, var`
    * `min, max`
    * `argmin, argmax`

In [ ]:
# example
arr = np.random.randn(3, 3, 3)

arr.sum()
np.sum(arr)
arr.sum(axis=0)  # along axis 0
np.sum(arr, axis=2)   # along axis 2

* cumulation: the intermediate results of aggregation
    * `cumsum` (cumulative sum, starting from 0)
    * `cumprod` (cumulative product, starting from 1)

In [89]:
# example
arr = np.arange(12).reshape(3,4)
print(arr)
arr.cumsum(axis=0)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21]], dtype=int32)

* In statistical methods, boolean values are coerced to 1 or 0.

In [94]:
# example
a = np.random.randn(100)
(a > 0).sum()  # number of positive values

57

* `any` (gives whether a boolean array has a True element)
* `all` (gives whether a boolean array consists of only True elements)

In [ ]:
a = np.array([False, False, True])
a.any()  # True
a.all()  # False

a = np.array([0, 0, 1])
a.any()  # True  (zero --> False, nonzero --> True) 
a.all()  # False (zero --> False, nonzero --> True)

## sorting

In [147]:
# in-place sorting
a = np.random.rand(5)
a.sort()  # sort `a` in-place

In [151]:
a = np.random.rand(9).reshape(3,3)
a.sort(axis=1)  # in-place sorting along axis 1
a

array([[0.21885836, 0.48705529, 0.60874074],
       [0.21434684, 0.41060988, 0.99562157],
       [0.73514598, 0.77576899, 0.94256389]])

In [109]:
# sorted copy
a = np.random.rand(5)
b = np.sort(a)  # return a sorted copy

In [ ]:
# example -- 5% quantile of array
arr = np.arange(100)
np.sort(arr)[ int(arr.shape[0] * 0.05) ]  # 5

## set operations on 1-dim. arrays

In [ ]:
# unique(x) -- returns sorted unique values in `x`
a = np.array([4,3,5,7,4,5,3])
np.unique(a)  # [3, 4, 5, 7]

In [ ]:
# in1d(x, y) -- returns a boolean array indicating whether each x[i] is contained in y
a = np.array([4,3,5,7,4,5,3])
np.in1d(a, np.arange(5))  # [True, True, False, False, True, False, True]

In [ ]:
# intersect1d(x, y) -- returns sorted, common unique elements of x and y
np.intersect1d([1,4,3,2,3], [6,2,3])  # [2, 3]

# union1d(x, y)  -- returns sorted union of x and y
np.union1d([3,2,3], [6,2,3])  # [2, 3, 6]

# setdiff1d(x, y) -- returned sorted array consists of unique elements in x that are not in y
np.setdiff1d([3,2,6,6], [2,3])  # [6]

# setxor1d(x, y) -- symmetric difference; elements that are in either x or y, but not both
np.setdiff1d([3,2,6,6], [1,3,1])  # [2, 6]

# Linear Algebra

In [9]:
# matrix multiplication
x = np.array([[1,2,3], [4,5,6]])
y = np.array([[6,23], [-1,7], [8,9]])

x.dot(y)
np.dot(x, y)  # same
x @ y  # same (since Python 3.5, NumPy 1.10)

array([[ 28,  64],
       [ 67, 181]])

In [11]:
# inverse matrix
m = np.array([[1.0,2,3], [4,5,0], [0,0,9]])

m_inv = np.linalg.inv(m)  # compute inverse matrix
np.dot(m_inv, m)

array([[1.00000000e+00, 0.00000000e+00, 2.22044605e-16],
       [0.00000000e+00, 1.00000000e+00, 2.22044605e-16],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])

Functions of `numpy.linalg` :
* `diag` (Return diagonal/off-diagonal elements of a square matrix as a 1D array, or convert a 1D array into a square matrix with zeros on the off-diagonal.) 
* `dot`  (matrix multiplication)
* `trace`
* `det`  (determinant)
* `inv`  (inverse of square matrix)
* `qr`  (QR decomposition)
* `svd`  (singluar value decomposition (SVD))
* `solve`  (Solve Ax = b for x, where A is a square matrix.)
* `lstsq`  (Compute the least-squares solution to Ax = b.)

# Pseudorandom Number Generation

In [14]:
np.random.normal(size=(3,3))  # returns 3x3 array of samples from standard normal distribution

array([[ 7.15060146e-01,  3.48520634e-01,  2.17937716e-01],
       [ 2.27889026e+00,  1.63717557e+00,  2.80013210e-02],
       [ 6.39058801e-01, -9.22341295e-01,  5.74611602e-04]])

In [ ]:
np.random.seed(1234)  # set random seed

In [ ]:
rand_gen = np.random.RandomState(1234)  # create a random number generator, isolated from others

rand_gen.rand(5)
rand_gen.randn(5)

Functions of `numpy.random` :
* `seed`
* `permutation`  (Return a random permutation of a sequence, or return a permuted range.)
* `shuffle`  (Randomly permute a sequence in-place.)
* `rand` (from uniform distribution over $[0,1)$), `randn` (from standard normal distribution)
* `randint`  (random integers given low-to-high range)
* `binomial` (binomial distribution), `normal`, `beta` (beta distribution), `chisquare` (chi-square distribution), `gamma` (gamma distribution), `uniform`

# Broadcasting
In an array operation like `a+b`, if the arrays do have the same shape, one or both of the arrays are extended (by repeating) to the same shape (without actually copying data) before the operation is carried out. 

In [36]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
b = np.array([-1,0,1])
a + b
# `b` is broadcasted to 
# [[-1,0,1]
#  [-1,0,1]]

array([[0, 2, 4],
       [3, 5, 7]])

In [39]:
b = np.array([[-1],
              [ 1]])
a + b
# `b` is broadcasted to 
# [[-1,-1,-1]
#  [ 1, 1, 1]]

array([[0, 1, 2],
       [5, 6, 7]])

In [41]:
a = np.array([1,2,3])
b = np.array([[-1],
              [ 1]])
a + b  # both `a` and `b` are broadcasted to shape 2x3

array([[0, 1, 2],
       [2, 3, 4]])

In [45]:
a = np.array([[1,2,3],
              [4,5,6]])
b = np.array([[0],
              [1],
              [2]])
#a + b  # won't work